train:
  # For forest models
  n_estimators: 10
  max_depth: 5
  # Neural network specific parameters
  x_size: 150
  y_size: 100
  max_iter: 1000
  # Common parameters
  test_size: 0.2
  seed: 1
  # Available pipelines: random_forest, gradient_boosting, neural_network
  pipeline: neural_network

