train:
  n_estimators: 110
  max_depth: 10
  test_size: 0.2
  seed: 1
  # Available pipelines: random_forest, gradient_boosting, neural_network
  pipeline: neural_network
  
  # Neural network specific parameters
  x_size: 100
  y_size: 50
  max_iter: 1000
